name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: true
      matrix:
        php: [8.1]
        laravel: [^8.0]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: jigear_testing
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
           composer update --prefer-dist --no-interaction --no-progress
      - name: Setup Laravel
        run: |
           cp .env.example .env
           cp .env.example .env.testing
           php artisan key:generate
           
      - name: Execute tests
        run: php artisan test
